site_name: Bidstream Documentation
site_description: Real-Time Bidding & Fraud Detection Platform
site_author: Justin Walker

theme:
  name: material
  logo: exports/BIDSTREAM_logo_no_bg_001.png
  favicon: exports/BIDSTREAM_logo_no_bg_001.png
  palette:
    scheme: slate
    primary: black
    accent: green
  icon:
    repo: material/arrow-left
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow

repo_url: https://walker-systems.github.io/
repo_name: Back to Portfolio

nav:
  - Home: index.md
  - Architecture Decisions: ADR.md
  - "Component: Bidding Engine": engine.md
  - "Component: Sentinel Service": sentinel.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
