global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bidding-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bidding-engine:8080']

  - job_name: 'sentinel-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sentinel-service:8081']
