server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: bidding-engine

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 100
          max-idle: 100
          min-idle: 10

  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: bidding-engine

logging:
  level:
    root: INFO
    com.walker.bidding: DEBUG
    org.springframework.data.redis: INFO
