spring:
  application:
    name: bidding-engine

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 100
          max-idle: 100
          min-idle: 10

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo

  main:
    web-application-type: reactive

logging:
  level:
    root: INFO
    com.walker.bidding: DEBUG
    org.springframework.data.redis: INFO
