server:
  port: 8081

spring:
  application:
    name: sentinel-service

  data:
    redis:
      host: localhost
      port: 6379
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    org.springframework.data.redis: DEBUG
