server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: sentinel-service

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.data.redis: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: sentinel-service
